---
version: "3"
services:
  db:
    image: dbimage
    ports:
      - "3306:3306"
  auth_service:
    image: authimage
    ports:
      - "1111:5001"
  book_service:
    image: bookimage
    ports:
      - "2222:5002"
  borrow_service:
    image: borrowimage
    ports:
      - "3333:5003"
  frontend_service:
    image: frontendimage
    ports:
      - "4444:5000"
